Repository ericcornelissen/git-tag-annotation-action, pull requests merged in 2022-10, with the labels that each got.

#333 Bump @actions/core from 1.9.1 to 1.10.0
  CHANGELOG.md
  package-lock.json
  package.json
  rollup.config.js
Labels: dependencies

#316 General minor changes
  .depcheckrc.json
  .depcheckrc.yml
  .fossa.yml
  .github/workflows/check.yml
  .github/workflows/release.yml
  .gitignore
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  SECURITY.md
  lib/.gitignore
  package.json
  rollup.config.js
  script/hooks/pre-commit
Labels: documentation, meta, ci/cd

#336 Add missing link definition to the README
  README.md
Labels: documentation

#338 Update the Contributing Guidelines
  CONTRIBUTING.md
Labels: meta

#339 Create "audit" commands
  .github/workflows/reusable-audit.yml
  CONTRIBUTING.md
  package.json
Labels: meta

#340 Rename Gitleaks audit to Secrets audit
  .github/workflows/reusable-audit.yml
Labels: ci/cd

#355 Use audit scripts in reusable audit workflow
  .github/workflows/reusable-audit.yml
Labels: ci/cd

#357 Update license check in CI to use the Fossa Action
  .github/workflows/check.yml
Labels: ci/cd

#360 Update deprecated set-output feature in release workflow
  .github/workflows/release.yml
Labels: ci/cd

#365 Use `licensee` for license scanning
  .fossa.yml
  .github/workflows/check.yml
  .licensee.json
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: dependencies, meta, ci/cd

#371 Add Prettier configuration
  .prettierrc.yml
Labels: meta

#363 Create devcontainer specification for this project
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: meta
